#!/bin/bash
set -e
set -x

LIBSNARK_FLAGS="-DUSE_ASM=ON -DCURVE=ALT_BN128 -DWITH_PROCPS=OFF -DWITH_SUPERCOP=OFF -DBINARY_OUTPUT=OFF"
LIBFQFFT_SRC=${LIBFQFFT_SRC:-https://github.com/scipr-lab/libfqfft.git}
LIBSNARK_SRC=${LIBSNARK_SRC:-https://github.com/scipr-lab/libsnark.git}
[ ! -d libsnark ] && git clone $LIBSNARK_SRC libsnark
cd libsnark 
git pull
git submodule init && git submodule update
[ ! -d build ] && mkdir build 
cd build && cmake $LIBSNARK_FLAGS ..
make
[ ! -d install ] && mkdir install 
DESTDIR=./install make install 
cd ..
[ ! -d libfqfft ] && git clone $LIBFQFFT_SRC libfqfft
cd libfqfft
git pull
git submodule init && git submodule update
[ ! -d build ] && mkdir build 
cd build 
[ ! -d install ] && mkdir install 
cmake .. -DCMAKE_INSTALL_PREFIX=./install
make
make install

